#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "current_branch" = "main" ]; then
  npm test
fi

npx --no -- commitlint --from=main --quiet
