#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# echo "Running pre-commit hook"

# 检查变动的文件:此处不知为何该句报错
changedFiles=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$')

# 定义需要进行测试的文件夹
testDirs=("src" "test")

# 判断是否进行测试
shouldTest=false

for file in $changedFiles; do
  for dir in "${testDirs[@]}"; do
    if [[ $file == $dir/**/* || $file == $dir/* ]]; then
      shouldTest=true
      break 2  # 跳出外层和内层循环
    fi
  done
done

# 运行测试，生成测试报告
if [ "$shouldTest" = true ]; then
  npm test

  # 将测试报告放到暂存区，一起提交
  git add coverage
fi

# 运行代码风格检查
npx --no -- commitlint --from=main --quiet
